import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import FabContact from "@/components/FabContact";

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-work-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${workSans.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        {children}
        <FabContact />
      </body>
    </html>
  );
}
